# Generated by Django 2.0.3 on 2018-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('student_id', models.CharField(max_length=7, verbose_name='Student ID')),
                ('message_url', models.URLField(max_length=256, verbose_name='Message URL')),
            ],
        ),
    ]
